// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Alquileres.Domain.Common;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Alquileres.Domain.Entities;

public partial class Alquiler : BaseEntity
{
    public string Code { get; set; }

    public int IdCliente { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Fecha { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime FechaFin { get; set; }

    public int Dias { get; set; }

    public int IdFormaPago { get; set; }

    public virtual Cliente ClienteNavigation { get; set; }

    public virtual FormaPago FormaPagoNavigation { get; set; }

    public virtual ICollection<LineasAlquiler> LineasAlquileres { get; set; } = new List<LineasAlquiler>();
}