// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Alquileres.Domain.Common;
using System;
using System.Collections.Generic;

namespace Alquileres.Domain.Entities;

public partial class Cliente : BaseEntity
{
    public string Code { get; set; }

    public DateTime FechaAlta { get; set; }

    public string Nombre { get; set; }

    public string Apellidos { get; set; }

    public string Dni { get; set; }

    public DateTime? FechaNacimiento { get; set; }

    public string Telefono { get; set; }

    public string Email { get; set; }

    public string Comentario { get; set; }

    public bool Activado { get; set; }

    public string Documento { get; set; }

    public virtual ICollection<Alquiler> Alquileres { get; set; } = new List<Alquiler>();
}