// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Alquileres.Domain.Common;

using System;
using System.Collections.Generic;

namespace Alquileres.Domain.Entities;

public partial class FormaPago: BaseEntity
{
    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public bool Activado { get; set; }

    public virtual ICollection<Alquiler> Alquileres { get; set; } = new List<Alquiler>();
}