// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Alquileres.Domain.Common;
using System;
using System.Collections.Generic;

namespace Alquileres.Domain.Entities;

public partial class LineasGenero : BaseEntity
{
    public int IdVideojuego { get; set; }

    public int IdGenero { get; set; }

    public virtual Genero GeneroNavigation { get; set; }

    public virtual VideoJuego VideojuegoNavigation { get; set; }
}