// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Alquileres.Domain.Common;
using System;
using System.Collections.Generic;

namespace Alquileres.Domain.Entities;

public partial class Plataforma : BaseEntity
{

    public string Nombre { get; set; }

    public string Version { get; set; }

    public string Company { get; set; }

    public bool Activado { get; set; }

    public virtual ICollection<PrecioVideoJuego> PrecioVideoJuegos { get; set; } = new List<PrecioVideoJuego>();
}