// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Alquileres.Domain.Common;
using System;
using System.Collections.Generic;

namespace Alquileres.Domain.Entities;

public partial class PrecioVideoJuego : BaseEntity
{

    public int IdVideoJuego { get; set; }

    public int IdPlataforma { get; set; }

    public decimal Precio { get; set; }

    public bool Activado { get; set; }

    public virtual Plataforma PlataformaNavigation { get; set; }

    public virtual VideoJuego VideoJuegoNavigation { get; set; }

    public virtual ICollection<LineasAlquiler> LineasAlquileres { get; set; } = new List<LineasAlquiler>();
}