// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Alquileres.Domain.Common;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Alquileres.Domain.Entities;

public partial class VideoJuego : BaseEntity
{

    public string Nombre { get; set; }

    [Column(TypeName ="datetime")]
    public DateTime? FechaLanzamiento { get; set; }

    public decimal? Volumen { get; set; }

    public string? Descripcion { get; set; }

    public string? Desarrollador { get; set; }

    public string? Pegi { get; set; }

    public bool Activado { get; set; }

    public string? Imagen { get; set; }

    public virtual ICollection<LineasGenero> LineasGeneros { get; set; } = new List<LineasGenero>();

    public virtual ICollection<PrecioVideoJuego> PrecioVideoJuegos { get; set; } = new List<PrecioVideoJuego>();
}