//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alquileres.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppApiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppApiResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alquileres.Application.Resources.AppApiResource", typeof(AppApiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: Company exception.
        /// </summary>
        public static string BaseController_CompanyException {
            get {
                return ResourceManager.GetString("BaseController.CompanyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: Email exception.
        /// </summary>
        public static string BaseController_EmailException {
            get {
                return ResourceManager.GetString("BaseController.EmailException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: Mediator exception.
        /// </summary>
        public static string BaseController_MediatorException {
            get {
                return ResourceManager.GetString("BaseController.MediatorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: UserId exception.
        /// </summary>
        public static string BaseController_UserIdException {
            get {
                return ResourceManager.GetString("BaseController.UserIdException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al crear el {0}, no se puede dar de alta un {0} con el mismo CIF/NIF..
        /// </summary>
        public static string CreateAuthorsCommandHandler_AuthorValidation {
            get {
                return ResourceManager.GetString("CreateAuthorsCommandHandler.AuthorValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La dirección seleccionada tiene presupuestos asociados y no puede ser eliminada..
        /// </summary>
        public static string DeleteAddressesCommandHandler_AddressesValidationFkBudget {
            get {
                return ResourceManager.GetString("DeleteAddressesCommandHandler.AddressesValidationFkBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La dirección seleccionada tiene facturas asociadas y no puede ser eliminada..
        /// </summary>
        public static string DeleteAddressesCommandHandler_AddressesValidationFkInvoice {
            get {
                return ResourceManager.GetString("DeleteAddressesCommandHandler.AddressesValidationFkInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cliente o proveedor tiene direcciones asociadas y no puede ser eliminado..
        /// </summary>
        public static string DeleteAuthorsCommandHandler_AuthorValidationFkAddresses {
            get {
                return ResourceManager.GetString("DeleteAuthorsCommandHandler.AuthorValidationFkAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cliente tiene presupuestos asociados y no puede ser eliminado..
        /// </summary>
        public static string DeleteAuthorsCommandHandler_AuthorValidationFkBudget {
            get {
                return ResourceManager.GetString("DeleteAuthorsCommandHandler.AuthorValidationFkBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proveedor tiene gastos asociados y no puede ser eliminado..
        /// </summary>
        public static string DeleteAuthorsCommandHandler_AuthorValidationFkExpenses {
            get {
                return ResourceManager.GetString("DeleteAuthorsCommandHandler.AuthorValidationFkExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cliente tiene facturas asociadas y no puede ser eliminado..
        /// </summary>
        public static string DeleteAuthorsCommandHandler_AuthorValidationFkInvoice {
            get {
                return ResourceManager.GetString("DeleteAuthorsCommandHandler.AuthorValidationFkInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede eliminar la serie al tener presupuestos asociados..
        /// </summary>
        public static string DeleteDocumentReferencesCommandHandler_DocumentReferencesBudgetValidation {
            get {
                return ResourceManager.GetString("DeleteDocumentReferencesCommandHandler.DocumentReferencesBudgetValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede eliminar la serie al tener gastos asociados..
        /// </summary>
        public static string DeleteDocumentReferencesCommandHandler_DocumentReferencesExpenseValidation {
            get {
                return ResourceManager.GetString("DeleteDocumentReferencesCommandHandler.DocumentReferencesExpenseValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede eliminar la serie al tener facturas asociadas..
        /// </summary>
        public static string DeleteDocumentReferencesCommandHandler_DocumentReferencesInvoiceValidation {
            get {
                return ResourceManager.GetString("DeleteDocumentReferencesCommandHandler.DocumentReferencesInvoiceValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato de archivo no válido..
        /// </summary>
        public static string GetExpensesFromFormRecognizerDocumentQueryHandler_InvalidFormat {
            get {
                return ResourceManager.GetString("GetExpensesFromFormRecognizerDocumentQueryHandler.InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha detectado ningún dato válido en el documento..
        /// </summary>
        public static string GetExpensesFromFormRecognizerDocumentQueryHandler_PristineObject {
            get {
                return ResourceManager.GetString("GetExpensesFromFormRecognizerDocumentQueryHandler.PristineObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe el archivo en Azure Storage..
        /// </summary>
        public static string GetFileByExpenseIdQueryHandler_AzureStorageFileNotFound {
            get {
                return ResourceManager.GetString("GetFileByExpenseIdQueryHandler.AzureStorageFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encuentra el gasto..
        /// </summary>
        public static string GetFileByExpenseIdQueryHandler_ExpenseNotFound {
            get {
                return ResourceManager.GetString("GetFileByExpenseIdQueryHandler.ExpenseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encuentra el nombre de archivo..
        /// </summary>
        public static string GetFileByExpenseIdQueryHandler_FilenameNotFound {
            get {
                return ResourceManager.GetString("GetFileByExpenseIdQueryHandler.FilenameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total presupuestado.
        /// </summary>
        public static string GetHomeSummaryInfoHandler_BudgetsTypeEvolutionBudgets {
            get {
                return ResourceManager.GetString("GetHomeSummaryInfoHandler.BudgetsTypeEvolutionBudgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total presupuestado aprobado.
        /// </summary>
        public static string GetHomeSummaryInfoHandler_BudgetsTypeEvolutionBudgetsApproved {
            get {
                return ResourceManager.GetString("GetHomeSummaryInfoHandler.BudgetsTypeEvolutionBudgetsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total presupuestado no aprobado.
        /// </summary>
        public static string GetHomeSummaryInfoHandler_BudgetsTypeEvolutionBudgetsNonApproved {
            get {
                return ResourceManager.GetString("GetHomeSummaryInfoHandler.BudgetsTypeEvolutionBudgetsNonApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gastos de cliente.
        /// </summary>
        public static string GetHomeSummaryInfoHandler_ClientExpensesEvolution {
            get {
                return ResourceManager.GetString("GetHomeSummaryInfoHandler.ClientExpensesEvolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gastos de compañía.
        /// </summary>
        public static string GetHomeSummaryInfoHandler_CompanyExpensesEvolution {
            get {
                return ResourceManager.GetString("GetHomeSummaryInfoHandler.CompanyExpensesEvolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gastos cliente.
        /// </summary>
        public static string GetHomeSummaryInfoHandler_ExpensesTypeEvolutionClient {
            get {
                return ResourceManager.GetString("GetHomeSummaryInfoHandler.ExpensesTypeEvolutionClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gastos compañía.
        /// </summary>
        public static string GetHomeSummaryInfoHandler_ExpensesTypeEvolutionOwn {
            get {
                return ResourceManager.GetString("GetHomeSummaryInfoHandler.ExpensesTypeEvolutionOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturas pagadas.
        /// </summary>
        public static string GetHomeSummaryInfoHandler_InvoiceEvolution {
            get {
                return ResourceManager.GetString("GetHomeSummaryInfoHandler.InvoiceEvolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha final no puede ser menor a la fecha inicial..
        /// </summary>
        public static string HomeValidationDate {
            get {
                return ResourceManager.GetString("HomeValidationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recibo.
        /// </summary>
        public static string PaymentMethods_BankReceipt {
            get {
                return ResourceManager.GetString("PaymentMethods.BankReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transferencia bancaria.
        /// </summary>
        public static string PaymentMethods_BankTransfer {
            get {
                return ResourceManager.GetString("PaymentMethods.BankTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bizum.
        /// </summary>
        public static string PaymentMethods_Bizum {
            get {
                return ResourceManager.GetString("PaymentMethods.Bizum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Con tarjeta.
        /// </summary>
        public static string PaymentMethods_Card {
            get {
                return ResourceManager.GetString("PaymentMethods.Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personalizado.
        /// </summary>
        public static string PaymentMethods_Custom {
            get {
                return ResourceManager.GetString("PaymentMethods.Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede establecer la dirección como NO fiscal, ya que tiene que existir una como tal.
        /// </summary>
        public static string UpdateAddressesCommandHandler_AddressMissing {
            get {
                return ResourceManager.GetString("UpdateAddressesCommandHandler.AddressMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al actualizar el {0}, CIF/NIF ya existe..
        /// </summary>
        public static string UpdateAuthorsCommandHandler_AuthorValidation {
            get {
                return ResourceManager.GetString("UpdateAuthorsCommandHandler.AuthorValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede editar un presupuesto finalizado..
        /// </summary>
        public static string UpdateBudgetsCommandHandler_BudgetValidationFinished {
            get {
                return ResourceManager.GetString("UpdateBudgetsCommandHandler.BudgetValidationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede modificar la serie al tener presupuestos asociados..
        /// </summary>
        public static string UpdateDocumentReferencesCommandHandler_DocumentReferencesBudgetValidation {
            get {
                return ResourceManager.GetString("UpdateDocumentReferencesCommandHandler.DocumentReferencesBudgetValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede modificar la serie al tener gastos asociados..
        /// </summary>
        public static string UpdateDocumentReferencesCommandHandler_DocumentReferencesExpenseValidation {
            get {
                return ResourceManager.GetString("UpdateDocumentReferencesCommandHandler.DocumentReferencesExpenseValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede modificar la serie al tener facturas asociadas..
        /// </summary>
        public static string UpdateDocumentReferencesCommandHandler_DocumentReferencesInvoiceValidation {
            get {
                return ResourceManager.GetString("UpdateDocumentReferencesCommandHandler.DocumentReferencesInvoiceValidation", resourceCulture);
            }
        }
    }
}
